name: Portfolio Updater
run-name: ${{ github.actor }} is running Netlify build!
on: 
  schedule:
    - cron: '*/10 * * * *'
jobs:
  Update-Portfolio-By-Running-Netlify-Build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_HOOK_ID }}
