name: Portfolio Updater
run-name: ${{ github.actor }} is running Vercel build and deploy!
on: 
  schedule:
    - cron: '*/12 * * * *'
  workflow_dispatch:
jobs:
  Update-Portfolio:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d '{}' ${{ secrets.BUILD_HOOK_VERCEL }}
